protected/models/Task.php
<?php
/**
 *@copyright : ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 *@author    : Shiv Charan Panjeta < shiv@toxsl.com >
 *
 * All Rights Reserved.
 * Proprietary and confidential :  All information contained herein is, and remains
 * the property of ToXSL Technologies Pvt. Ltd. and its partners.
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 *
 */

/**
 * This is the model class for table "tbl_task".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $case_id
 * @property integer $type_id
 * @property integer $state_id
 * @property integer $platform_id
 * @property integer $department_id
 * @property string $start_date
 * @property string $end_date
 * @property string $estimated_time
 * @property string $actual_time
 * @property string $created_on
 * @property string $updated_on
 * @property integer $assign_to_id
 * @property integer $created_by_id === Related data ===
 * @property User $assignTo
 * @property Case $case
 * @property User $createdBy
 * @property Department $department
 * @property Platform $platform
 * @property TaskTimer[] $taskTimers
 */
namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class Task extends \app\components\TActiveRecord
{

    public $taskDetail;

    public function __toString()
    {
        return (string) $this->title;
    }

    public static function getCaseOptions()
    {
        return ArrayHelper::Map(Cases::find()->all(), 'id', 'title');
    }

    public static function getTypeOptions()
    {
        return [
            "TYPE1",
            "TYPE2",
            "TYPE3"
        ];
    }

    public function isAllowed()
    {
        if (User::isAdmin())
            return true;
        if (User::isEmployee())
            return true;
        if (User::isClient())
            return true;
        if (User::isQualityControl())
            return true;
        if (User::isManager())
            return true;
        if ($this instanceof User) {
            return ($this->id == Yii::$app->user->id);
        }
        if ($this->hasAttribute('created_by_id')) {
            return ($this->created_by_id == Yii::$app->user->id);
        }

        if ($this->hasAttribute('user_id')) {
            return ($this->user_id == Yii::$app->user->id);
        }

        return false;
    }

    public function getType()
    {
        $list = self::getTypeOptions();
        return isset($list[$this->type_id]) ? $list[$this->type_id] : 'Not Defined';
    }

    const STATE_ASSIGNED = 1;

    const STATE_INPROGRESS = 2;

    const STATE_CLOSED = 3;

    const STATE_IN_REVIEW = 4;

    const STATE_ON_HOLD = 5;

    const STATE_PENDING = 6;

    const STATE_COMPLETED = 7;

    const SCENARIO_ASSIGN_TASK = "assign-task";

    const SCENARIO_UPDATE_TASK = "update-task";

    public static function getStateOptions()
    {
        return [
            self::STATE_ASSIGNED => "Assigned",
            self::STATE_INPROGRESS => "In-Progress",
            self::STATE_CLOSED => "Closed",
            self::STATE_ON_HOLD => "Hold",
            self::STATE_PENDING => "Pending",
            self::STATE_COMPLETED => "Completed",
            self::STATE_IN_REVIEW => "In-Review"
        ];
    }

    public function getState()
    {
        $list = self::getStateOptions();
        return isset($list[$this->state_id]) ? $list[$this->state_id] : 'Not Defined';
    }

    public function getStateBadge()
    {
        $list = [
            self::STATE_ASSIGNED => "info",
            self::STATE_INPROGRESS => "primary",
            self::STATE_CLOSED => "success",
            self::STATE_PENDING => "danger",
            self::STATE_ON_HOLD => "info",
            self::STATE_COMPLETED => "success",
            self::STATE_IN_REVIEW => "new"
        ];
        return isset($list[$this->state_id]) ? \yii\helpers\Html::tag('span', $this->getState(), [
            'class' => 'label label-' . $list[$this->state_id]
        ]) : 'Not Defined';
    }

    public static function getActionOptions()
    {
        return [
            self::STATE_ASSIGNED => "Assigned",
            self::STATE_INPROGRESS => "In-Progress",
            self::STATE_CLOSED => "Completed",
            self::STATE_PENDING => "Pending",
            self::STATE_ON_HOLD => "Hold",
            self::STATE_COMPLETED => "completed",
            self::STATE_IN_REVIEW => "In-review"
        ];
    }

    public function getTotalTaskTime()

    {
        $model = TaskEvent::find()->where([
            'created_by_id' => \Yii::$app->user->id,
            'task_id' => $this->id
        ])->sum('time_difference');

        if (! empty($model)) {

            return gmdate("H:i:s", $model);
        }
        return 0;
    }

    public function getTaskExtraTime()
    {
        $model = TaskEvent::find()->where([
            'created_by_id' => \Yii::$app->user->id,
            'task_id' => $this->id
        ])->sum('time_difference');

        if (! empty($model)) {
            $task = Task::findOne($this->id);
            if (! empty($task)) {
                $actual_time = gmdate("H:i:s", $model);
                $actual_times = strtotime($actual_time);
                $estimated_time = strtotime($task->estimated_time);
                $difference = (($estimated_time) - ($actual_times));
                return $extra_time = gmdate("H:i:s", $difference);
            } else {

                $extra_time = 0;
            }
        }
        return $extra_time;
    }

    public function getTimerStatus()
    {
        $timer = Timer::find()->where([
            'task_id' => $this->id,
            'state_id' => Timer::STATE_START
        ])->one();
        if ($timer != null) {
            return Html::tag('span', 'Running', [
                'class' => 'badge badge-success'
            ]);
        }
        return Html::tag('span', 'Stopped', [
            'class' => 'badge badge-success'
        ]);
    }

    public function getTimerStatusApp()
    {
        $timer = Timer::find()->where([
            'task_id' => $this->id,
            'state_id' => Timer::STATE_START
        ])->one();
        if ($timer != null) {
            return Timer::STATE_START;
        }
        return Timer::STATE_STOP;
    }

    public function getActualTime()
    {
        $this->actual_time = $this->getTimers()
            ->where([
            'state_id' => Timer::STATE_STOP
        ])
            ->sum('work_time');

        if (is_null($this->actual_time)) {
            $this->actual_time = 0;
        }
        $this->updateAttributes([
            'actual_time'
        ]);

        return Yii::$app->formatter->asDuration($this->actual_time);
    }

    public function getActualTimeApp()
    {
        $this->actual_time = $this->getTimers()
            ->where([
            'state_id' => Timer::STATE_STOP
        ])
            ->sum('work_time');

        if (is_null($this->actual_time)) {
            $this->actual_time = 0;
        }
        $this->updateAttributes([
            'actual_time'
        ]);
        return gmdate("H:i:s", $this->actual_time);
    }

    public function getEvents($type_id = null)
    {
        $start_date = date("Y-m-d ", strtotime($this->date));
        $end_date = date("Y-m-d 08:00:00", strtotime(' +1 day', strtotime($this->date)));
        $query = TaskEvent::find()->where([

            'user_id' => $this->user_id
        ])->andWhere([
            'between',
            'created_on',
            $start_date,
            $end_date
        ]);

        if (isset($type_id)) {

            $query->andWhere([
                'type_id' => $type_id
            ]);
        }
        return $query;
    }

    public static function getPlatformOptions()
    {
        return ArrayHelper::Map(Platform::findActive()->each(), 'id', 'title');
    }

    public static function getDepartmentOptions()
    {
        return ArrayHelper::Map(Department::findActive()->each(), 'id', 'title');
    }

    public static function getAssignToOptions()
    {
        return ArrayHelper::Map(User::findActive()->where([
            '!=',
            'role_id',
            [
                User::ROLE_ADMIN,
                User::ROLE_CLIENT
            ]
        ])->each(), 'id', 'full_name');
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord) {
            if (empty($this->start_date)) {
                $this->start_date = date('Y-m-d');
            }
            if (empty($this->end_date)) {
                $this->end_date = date('Y-m-d');
            }
            if (empty($this->created_on)) {
                $this->created_on = date('Y-m-d H:i:s');
            }
            if (empty($this->updated_on)) {
                $this->updated_on = date('Y-m-d H:i:s');
            }
            if (empty($this->created_by_id)) {
                $this->created_by_id = self::getCurrentUser();
            }
        } else {
            $this->updated_on = date('Y-m-d H:i:s');
        }
        return parent::beforeValidate();
    }

    public static function getTaskStatus($state)
    {
        return self::find()->where([
            'assign_to_id' => Yii::$app->user->id,
            'state_id' => $state
        ])->count();
    }

    /**
     *
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%task}}';
    }

    /**
     *
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'title',
                    'description',
                    'case_id',
                    'platform_id',
                    // 'department_id',
                    'start_date',
                    'estimated_time',
                    'assign_to_id',
                    'created_by_id'
                ],
                'required'
            ],
            [
                [
                    'description'

protected/controllers/DashboardController.php
<?php

/**
 *@copyright : ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 *@author	 : Shiv Charan Panjeta < shiv@toxsl.com >
 */
namespace app\controllers;

use app\components\TController;
use app\models\User;
use yii\filters\AccessControl;
use app\models\Setting;
use app\models\search\User as UserSearch;
use app\models\search\Task;

class DashboardController extends TController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'default-data'
                        ],
                        'allow' => true,
                        'matchCallback' => function () {
                            return User::isAdmin();
                        }
                    ],
                    [
                        'actions' => [
                            'hr-index',
                            'index'
                        ],
                        'allow' => true,
                        'matchCallback' => function () {
                            return User::isHR();
                        }
                    ],
                    [
                        'actions' => [
                            'employee-index',
                            'index'
                        ],
                        'allow' => true,
                        'matchCallback' => function () {
                            return User::isEmployee();
                        }
                    ],
                    [
                        'actions' => [
                            'manager-index',
                            'index'
                        ],
                        'allow' => true,
                        'matchCallback' => function () {
                            return User::isManager();
                        }
                    ]
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        if (User::isHR()) {
            return $this->redirect([
                'hr-index'
            ]);
        } else if (User::isEmployee()) {
            return $this->redirect([
                'employee-index'
            ]);
        } else if (User::isClient()) {
            return $this->redirect([
                '/client/index'
            ]);
        } else if (User::isManager()) {
            return $this->redirect([
                'manager-index'
            ]);
        }
        $this->updateMenuItems();
        $smtpConfig = isset(\Yii::$app->settings) ? \Yii::$app->settings->smtp : null;
        if (empty($smtpConfig)) {
            Setting::setDefaultConfig();
        }
        return $this->render('index');
    }

    public function actionHrIndex()
    {
        $user = new User();
        $searchModel = new UserSearch();
        $post = \Yii::$app->request->post();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams, User::ROLE_EMPLOYEE, $post);
        $this->updateMenuItems();

        return $this->render('employee-list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'user' => $user,
            'search' => $post
        ]);
    }

    public function actionEmployeeIndex()
    {
        $searchModel = new Task();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('employee-dashboard', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionManagerIndex()
    {
        $searchModel = new \app\models\search\Cases();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        $dataProvider->pagination->pageSize = 10;
        return $this->render('manager-dashboard', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    public static function MonthlySignups()
    {
        $date = new \DateTime();
        $date->modify('-12  months');
        $count = array();
        for ($i = 1; $i <= 12; $i ++) {
            $date->modify('+1 months');
            $month = $date->format('Y-m');

            $count[$month] = (int) User::find()->where([
                'like',
                'created_on',
                $month
            ])
                ->andWhere([
                '!=',
                'role_id',
                User::ROLE_ADMIN
            ])
                ->count();
        }
        return $count;
    }

    public function actionDefaultData()
    {
        Setting::setDefaultConfig();
        $msg = 'Done !! Setting reset succefully!!!';
        \Yii::$app->session->setFlash('success', $msg);
        return $this->redirect(\Yii::$app->request->referrer);
    }
}

protected/views/dashboard/_employee-list.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>

<?php
/** @var $model **/
?>
<div class="profile-widget">
	<div class="profile-img">
		<a href="<?= $model->getUrl('view-employee')?>" class="avatar"><?=$model->displayImage($model->profile_file, [], 'default.jpg', true);?> </a>
	</div>

	<div class="dropdown profile-action">
		<a href="javascript:void(0);" class="action-icon dropdown-toggle"
			data-toggle="dropdown" aria-expanded="false"><i
			class="fa fa-ellipsis-v"></i></a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="dropdown-item"
				href="<?= Url::toRoute(['/user/update-employee' , 'id' => $model->id])?>"><i
				class="fa fa-pencil m-r-5"></i> Edit</a> 
				
			
												<?php
            $options = [
                'title' => Yii::t('app', 'Delete'),
                'aria-label' => Yii::t('app', 'Delete'),
                'data-pjax' => '0',
                'class' => 'dropdown-item showActionModalButton',
                'data-id' => $model->id,
                'value' => Url::toRoute([
                    '/user/delete-employee',
                    'id' => $model->id
                ])
            ];

            echo Html::a('<i class="fa fa-trash-o m-r-5"></i>Delete', false, $options);
            ?>
			
		</div>
	</div>
	<h4 class="user-name m-t-10 mb-0 text-ellipsis">
		<a href="<?= $model->getUrl('view-employee')?>"><?= !empty($model->full_name) ? $model->full_name : ''?></a>
	</h4>
	<div class="small text-muted"><?= !empty($model->department) ? $model->department->title : ''?></div>
</div>

protected/views/dashboard/_taskList.php
<?php
use yii\helpers\Html;
use app\models\User;
?>
<tr>
	<td><?= Html::encode($model->id) ?></td>
	<td><?= Html::encode($model->title) ?></td>
	<td><?= Html::encode(!empty($model->case)?$model->case->title:"") ?></td>
	<td><span class="badge badge-success"><?= $model->getTimerStatus(); ?></span></td>
	<td class="sorting_1">
		<h2 class="table-avatar">
			<a href="#0"><?= Html::encode(!empty($model->assignTo)?$model->assignTo->full_name:"") ?> <span>Web
					Designer</span></a>
		</h2>
	</td>
	<td><?= Html::encode($model->estimated_time) ?> hrs</td>
	<td><?= !empty($model->actual_time)? Html::encode($model->actualTime):"not set" ?> </td>
	<td><?= Html::encode(date("d M Y",strtotime($model->created_on))) ?></td>
	<td class="text-right">
		<div class="dropdown dropdown-action">
			<a href="#" class="action-icon dropdown-toggle"
				data-toggle="dropdown" aria-expanded="false"><i
				class="la la-ellipsis-v"></i></a>
			<div class="dropdown-menu dropdown-menu-right">
				<a class="dropdown-item" href="<?= $model->getUrl('view') ?>"><i
					class="fa fa-eye m-r-5"></i> View</a>
								</div>
		</div>
	</td>
</tr>

protected/views/dashboard/employee-dashboard.php
    <?php

	use app\models\LeaveRequest;
	use app\models\Ticket;
	use app\models\Task;
	use app\models\Team;
	use yii\helpers\Url;
	use yii\widgets\ListView;
	?>

    <!-- Page Header -->
    <div class="page-header">
    	<div class="row">
    		<div class="col-sm-12">
    			<h3 class="page-title">Welcome <?= !empty(Yii::$app->user->identity) ? Yii::$app->user->identity->full_name : '' ?></h3>
    			<ul class="breadcrumb">
    				<li class="breadcrumb-item active">Dashboard</li>
    			</ul>
    		</div>
    	</div>
    </div>
    <!-- /Page Header -->

    <div class="row">
    	<div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
    		<div class="card dash-widget">
			<a href="<?= Url::toRoute(['cases/index']) ?>">
    			<div class="card-body">
    				<span class="dash-widget-icon"><i class="fa fa-cubes"></i></span>
    				<div class="dash-widget-info">
    					<h3><?= Team::find()->where(['user_id' => Yii::$app->user->id])->count() ?></h3>
    					<span>Projects</span>
    				</div>
				</div>
			</a>
    		</div>
    	</div>
    	<div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
    		<div class="card dash-widget">
    			<a href="<?= Url::toRoute(['task/index']) ?>">
    				<div class="card-body">
    					<span class="dash-widget-icon"><i class="fa fa-usd"></i></span>
    					<div class="dash-widget-info">
    						<h3><?= Task::find()->where(['assign_to_id' => Yii::$app->user->id])->count() ?></h3>
    						<span>Tasks</span>
    					</div>
    				</div>
    			</a>
    		</div>
    	</div>
    	<div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
    		<div class="card dash-widget">
    			<div class="card-body">
    				<span class="dash-widget-icon"><i class="fa fa-diamond"></i></span>
    				<div class="dash-widget-info">
    					<h3><?= LeaveRequest::find()->where(['created_by_id' => Yii::$app->user->id])->count() ?></h3>
    					<span>Leave Request</span>
    				</div>
    			</div>
    		</div>
    	</div>
    	<div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
    		<div class="card dash-widget">
    			<div class="card-body">
    				<span class="dash-widget-icon"><i class="fa fa-user"></i></span>
    				<div class="dash-widget-info">
    					<h3><?= Ticket::find()->where(['created_by_id' => Yii::$app->user->id])->count() ?></h3>
    					<span>Tickets</span>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>

    <!-- Statistics Widget -->
    <div class="row">
    	<div class="col-md-12 col-lg-12 col-xl-5 d-flex">
    		<div class="card flex-fill dash-statistics">
    			<div class="card-body">
    				<h5 class="card-title">Statistics</h5>
    				<div class="stats-list">
    					<div class="stats-info">
    						<p>
    							Today Leave <strong>4 <small>/ 65</small></strong>
    						</p>
    						<div class="progress">
    							<div class="progress-bar bg-primary" role="progressbar" style="width: 31%"></div>
    						</div>
    					</div>
    					<div class="stats-info">
    						<p>
    							Pending Invoice <strong>15 <small>/ 92</small></strong>
    						</p>
    						<div class="progress">
    							<div class="progress-bar bg-warning" role="progressbar" style="width: 31%"></div>
    						</div>
    					</div>
    					<div class="stats-info">
    						<p>
    							Completed Projects <strong>85 <small>/ 112</small></strong>
    						</p>
    						<div class="progress">
    							<div class="progress-bar bg-success" role="progressbar" style="width: 62%"></div>
    						</div>
    					</div>
    					<div class="stats-info">
    						<p>
    							Open Tickets <strong>190 <small>/ 212</small></strong>
    						</p>
    						<div class="progress">
    							<div class="progress-bar bg-danger" role="progressbar" style="width: 62%"></div>
    						</div>
    					</div>
    					<div class="stats-info">
    						<p>
    							Closed Tickets <strong>22 <small>/ 212</small></strong>
    						</p>
    						<div class="progress">
    							<div class="progress-bar bg-info" role="progressbar" style="width: 22%"></div>
    						</div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>

    	<div class="col-md-12 col-lg-6 col-xl-7 d-flex">
    		<div class="card flex-fill">
    			<div class="card-body">
    				<h4 class="card-title">Task Statistics</h4>
    				<div class="statistics">
    					<div class="row">
    						<div class="col-md-6 col-6 text-center">
    							<div class="stats-box mb-4">
    								<p>Total Tasks</p>
    								<h3><?= Task::find()->where(['assign_to_id' => Yii::$app->user->id])->count() ?></h3>
    							</div>
    						</div>
    						<div class="col-md-6 col-6 text-center">
    							<div class="stats-box mb-4">
    								<p>Overdue Tasks</p>
    								<h3>19</h3>
    							</div>
    						</div>
    					</div>
    				</div>
    				<div class="progress mb-4">
    					<div class="progress-bar bg-purple" style="width: 30%">30%</div>
    					<div class="progress-bar bg-warning" style="width: 22%">22%</div>
    					<div class="progress-bar bg-success" style="width: 24%">24%</div>
    					<div class="progress-bar bg-danger" style="width: 26%">21%</div>
    					<div class="progress-bar bg-info" style="width: 10%">10%</div>
    				</div>
    				<div>
    					<p>
    						<i class="fa fa-dot-circle-o text-purple mr-2"></i>Completed Tasks
    						<span class="float-right"><?= Task::getTaskStatus(Task::STATE_COMPLETED) ?></span>
    					</p>
    					<p>
    						<i class="fa fa-dot-circle-o text-warning mr-2"></i>Inprogress
    						Tasks <span class="float-right"><?= Task::getTaskStatus(Task::STATE_INPROGRESS) ?></span>
    					</p>
    					<p>
    						<i class="fa fa-dot-circle-o text-success mr-2"></i>On Hold Tasks
    						<span class="float-right"><?= Task::getTaskStatus(Task::STATE_ON_HOLD) ?></span>
    					</p>
    					<p>
    						<i class="fa fa-dot-circle-o text-danger mr-2"></i>Pending Tasks <span class="float-right"><?= Task::getTaskStatus(Task::STATE_PENDING) ?></span>
    					</p>
    					<p class="mb-0">
    						<i class="fa fa-dot-circle-o text-info mr-2"></i>Review Tasks <span class="float-right"><?= Task::getTaskStatus(Task::STATE_IN_REVIEW) ?></span>
    					</p>
    				</div>
    			</div>
    		</div>
    	</div>

    </div>
    <!-- /Statistics Widget -->

    <div class="row">

    	<div class="col-md-12 d-flex">
    		<div class="table-responsive">
    			<table class="table table-striped custom-table mb-0 ">
    				<thead>
    					<tr>
    						<th>ID</th>
    						<th>Task</th>
    						<th>Projects</th>
    						<th>Timer</th>
    						<th>Assign To</th>
    						<th>Estimate Time</th>
    						<th>Actual Time</th>
    						<th>Created On</th>
    						<th class="text-right">Actions</th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php

						echo ListView::widget([
							'dataProvider' => $dataProvider,
							'itemView' => '_taskList',
						]); ?>
    				</tbody>
    			</table>
    		</div>
    	</div>
    </div>
    <!-- /Page Content -->

protected/views/dashboard/employee-list.php
<?php
use yii\widgets\ListView;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Designation;
use app\components\TActiveForm;
use yii\helpers\Html;

/**
 *
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\User $searchModel
 * @var $user app\models\User
 */
?>

<!-- Page Header -->
<div class="page-header">
	<div class="row align-items-center">
		<div class="col">
			<h3 class="page-title">Employee List</h3>
			<ul class="breadcrumb">
				<li class="breadcrumb-item"><a href="<?= Url::home()?>">Home</a></li>
				<li class="breadcrumb-item active">Employee List</li>
			</ul>
		</div>
		<div class="col-auto float-right ml-auto">
			<a href="<?= Url::toRoute(['/user/add-employee'])?>"
				class="btn add-btn ml-2"><i class="fa fa-plus"></i> Add Employee</a>
		</div>
	</div>
</div>
<!-- /Page Header -->

<!-- Search Filter -->
<?php

$form = TActiveForm::begin([
    'id' => 'employee-search-form',
    'enableAjaxValidation' => false,
    'action' => Url::toRoute([
        '/dashboard/hr-index'
    ])
]);
?><div class="row filter-row">

	<div class="col-sm-6 col-md-3">
		<?=$form->field($user, 'employee_id', ['options' => ['class' => 'form-group form-focus']] )->textInput(['maxlength' => 55 , 'class' => 'form-control floating' , 'value' => !empty($search['User']['employee_id']) ? $search['User']['employee_id'] : ''])->label('Employee ID',['class'=>"focus-label"])?>
	</div>
	<div class="col-sm-6 col-md-3">
		<?=$form->field($user, 'full_name', ['options' => ['class' => 'form-group form-focus']] )->textInput(['maxlength' => 55 , 'class' => 'form-control floating', 'value' => !empty($search['User']['full_name']) ? $search['User']['full_name'] : ''])->label('Employee Name',['class'=>"focus-label"])?>
	</div>
	<div class="col-sm-6 col-md-3">
		<?= $form->field($user, 'designation', ['options' => ['class' => 'form-group form-focus select-focus focused']] )->dropDownList(ArrayHelper::Map(Designation::find()->all(), 'id', 'title') , ['prompt' => 'Select Designation', 'value' => !empty($search['User']['designation']) ? $search['User']['designation'] : ''])->label('Designation',['class'=>"focus-label"])?>
	</div>
	<div class="col-sm-6 col-md-3">
		<?=Html::submitButton( Yii::t('app', 'Search'), ['class' => 'btn btn-primary submit-btn'])?>
	</div>
</div>
<?php TActiveForm::end()?>
<!-- /Search Filter -->

<div class="staff-grid-row">

<?php

echo ListView::widget([
    'summary' => false,
    'dataProvider' => $dataProvider,

    'options' => [
        'class' => 'list-view row'
    ],

    'itemOptions' => [
        'class' => 'item col-md-4 col-sm-6 col-12 col-lg-4 col-xl-3'
    ],
    'itemView' => '_employee-list'
]);
?>

</div>
<!-- /Page Content -->